### PR TITLE
Added binary for Aarch64

### PR DESCRIPTION
**Pull request by PelleRavn**
I took the binary you create on the follow issue, and uploaded to the repo:
https://github.com/50ButtonsEach/fliclib-linux-hci/issues/62.

I have tested it, and it seem to be working just fine, so I have no idea why it haven't been added to the repo yet.

### CODE REVIEW

**Comment by PelleRavn** [comment]
Are you serious guys? It's been 5 months since I created this, and you haven't touched anything in the repo. People are trying to use your stuff, and you are just completely ignoring their needs or their help they hand you.

**Comment by Emill** [comment]
We are just about to release a new version, which will let you get info about a button's flic version and firmware version. This will be complied for aarch64 as well.

**Comment by PelleRavn** [comment]
> Sorry for not replying earlier. We are just about to release a new version, which will let you get info about a button's flic version and firmware version. This will be complied for aarch64 as well.

Thanks for the reply @Emill. That's good news, looking forward to the update.

**Comment by patrickkamin** [comment]
@Emill Any idea on when then new version will be available?

**Comment by Emill** [comment]
Now :)

**Comment by PelleRavn** [comment]
Closed as there now is a aarch64 binary available.
Thanks a lot!

**Pull request closed without merging**
